# buildspec.yml
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g aws-cdk
      - npm ci
  build:
    commands:
      # スタックの状態を確認
      - STACK_NAME=MyBlogCdkStack
      - STATUS=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query "Stacks[0].StackStatus" --output text || echo "NOT_FOUND")
      - |
        if [[ "$STATUS" == "CREATE_COMPLETE" || "$STATUS" == "UPDATE_COMPLETE" ]]; then
          echo "Stack already exists and is stable. Skipping cdk deploy."
        else
          echo "Deploying CDK stack..."
          cdk deploy --require-approval never
        fi
